library(readxl)
pl <- read_excel("C:/Users/ahfgc/OneDrive/Desktop/DS_dataset/cleaned_premier_league_data.xlsx")
View(pl)
summary(pl[, c("Gls", "Ast", "MP", "xG", "xAG")])
sd(pl$Gls)
sd(pl$Ast)
sd(pl$MP)
sd(pl$xG)
sd(pl$xAG)
aggregate(Gls ~ Pos, data = pl, mean)
aggregate(xG ~ Pos, data = pl, mean)
boxplot(Gls ~ Pos, data=pl,main="Goals by Position",xlab="Position",ylab="Goals")
aggregate(MP ~ Team, data=pl, sd)
cor(pl[, c("Gls", "Ast", "xG", "xAG", "MP")])
plot(pl$xG, pl$Gls,main="xG vs Goals",xlab="Expected Goals (xG)",ylab="Actual Goals (Gls)")
head(pl[order(pl$Gls, decreasing = TRUE), c("Player", "Team", "Gls", "xG")])
hist(pl$Gls, main="Distribution of Goals", xlab="Goals")
hist(pl$xG, main="Distribution of xG", xlab="xG")
barplot(pl$Player,names.arg = pl$Nation,main = "Player per nation", xlab = "Nation", ylab = "Player")
nation_count <- table(pl$Nation)
barplot(nation_count,main = "Players per Nation",xlab = "Nation",ylab = "Player Count",las = 2,cex.names = 0.7)
team_count <- table(pl$Team)
barplot(team_count,main = "Players per Team",xlab = "Team",ylab = "Player Count",las = 2,cex.names = 0.7)
set.seed(123)
train_index <- sample(1:nrow(pl), 0.7 * nrow(pl))
train <- pl[train_index, ]
test  <- pl[-train_index, ]

nrow(train)
nrow(test)
table(train$Pos)
table(test$Pos)

